### ISSUE TITLE
Incorrect default scale

### ISSUE THREAD

**Issue by AccidentalDisassembly** [net-lisias-ksp/TweakScaleCompanion_APlus#2]
In AirplanePlus-Propulsion_TweakScale.cfg, line ~115 - the defaultScale on the "mk3s1" part needs to be 1.25 rather than 0.625.

**Comment by Lisias** [comment]
Fixed on commit https://github.com/net-lisias-ksp/TweakScaleCompanion_APP/commit/b9d8aee68b14cd890b7b217f35b1e46ed2e4b619

Thanks for the heads up!!
